CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- TABLE:USERS
CREATE TABLE IF NOT EXISTS USERS
(
	UUID          UUID	DEFAULT uuid_generate_v4()	NOT NULL PRIMARY KEY,
	-------
	FIRSTNAME  VARCHAR(255),
	SURNAME   VARCHAR(255),
	MIDDLENAME VARCHAR(255),
	FIO VARCHAR(1024) GENERATED ALWAYS AS (SURNAME||' '||FIRSTNAME||' '||MIDDLENAME) STORED,
	SEX BOOLEAN,
	AGE	INTEGER,
	-------
	CREATE_TS   timestamp    NOT NULL,
	UPDATE_TS   timestamp
);

CREATE TABLE IF NOT EXISTS ORDERS
(
	UUID UUID DEFAULT uuid_generate_v4()	NOT NULL PRIMARY KEY,
	-------
	NUMBER SERIAL,
	-------
	CREATE_TS   timestamp    NOT NULL,
	UPDATE_TS   timestamp
);

CREATE TABLE IF NOT EXISTS PRODUCTS
(
	UUID UUID DEFAULT uuid_generate_v4()        NOT NULL PRIMARY KEY,
	-------
	DESCRIPTION VARCHAR(255),
	PRICE	jsonb,
	LEFT_IN_STOCK	INTEGER,
	CREATE_TS   timestamp    NOT NULL,
	UPDATE_TS   timestamp
);

CREATE TABLE IF NOT EXISTS USER_ORDER
(
	USER_ID UUID NOT NULL REFERENCES USERS (UUID) ON DELETE CASCADE,
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (UUID) ON DELETE CASCADE,
	UNIQUE (USER_ID, ORDER_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_ORDER
(
	ORDER_ID UUID NOT NULL REFERENCES ORDERS (UUID) ON DELETE CASCADE,
	PRODUCT_ID UUID NOT NULL REFERENCES PRODUCTS (UUID) ON DELETE CASCADE,
	COUNT INTEGER DEFAULT 1,
	UNIQUE (ORDER_ID, PRODUCT_ID)
);
